spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:device_management_be}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    properties:
      hibernate:
        format_sql: true
  liquibase:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:device_management_be}
    user: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

logging:
  level:
    org.hibernate.SQL: debug
